Btstack prepare for packet logs
raspberrypi/pico-examples pull request #425
Opened 2023-10-03 12:31 UTC by mringwal

When users have problems, the most efficient way is to analyze the packet logs. This PR makes it easier to enable the packet logger.

2023-10-03 12:35 UTC, peterharperuk commented
I'll switch this to develop if you don't mind.

2023-10-03 12:36 UTC, mringwal commented
Sorry, both should have been for 'develop'

2023-10-03 12:42 UTC, peterharperuk commented
We do some of this in the sdk https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/pico_cyw43_driver/btstack_cyw43.c#L54 where we also check ENABLE_SEGGER_RTT. Maybe we should call hci_dump_enable_packet_log in there as well?

2023-10-03 12:45 UTC, mringwal commented
I see. In this case, we can close this PR.
The logger is on by default, so that's fine, too.

The point is, how would people (incl. me) find this?

2023-10-03 12:56 UTC, mringwal commented
A README would be great!

2023-10-03 14:54 UTC, peterharperuk commented
Is this any good? https://github.com/raspberrypi/pico-examples/pull/427

2024-02-22 14:32 UTC, przymi requested changes

2024-02-24 11:43 UTC, mringwal commented on pico_w/bt/picow_bt_example_common.c
> +#if ENABLE_HCI_DUMP
Good point. Following the readme here https://github.com/raspberrypi/pico-examples/pull/427/commits/3ed9698551f24aa92649dc6edd627d449b4f2159 I've used `#if WANT_HCI_DUMP' in the PR.
Any progress with the readme? :)

2024-02-26 17:25 UTC, peterharperuk commented on pico_w/bt/picow_bt_example_common.c
> +#if ENABLE_HCI_DUMP
It's waiting for a review.

2025-02-13 17:02 UTC, peterharperuk commented
I think we did this? Please reopen if I'm wrong.

2025-02-13 17:02 UTC, closed without merging